language: php
sudo: false
services:
- mysql
cache:
  directories:
  - "$HOME/.composer/cache/files"
matrix:
  fast_finish: true
  include:
  - php: 7.3
env:
- SYMFONY_VERSION="4.0.*" DB=mysql
before-install:
- composer self-update
install:
- cp .env.travis.dist .env
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
notifications: 
email: eliram13jp@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: Q00JMY4kEE3hXj+HPSGm05q8jN1J1tMMj6vJDzW/amDVP+Vb8/xwOonR1hwdEv7Eb6jFQB22QtUvn8NfD3oLI7aMQ4bFOqbcse2+LTYpV7gKxtzPzKewmVUEHfCgZ3GJpgpjSeQfOUBBylLdmK3a3aTmBXEa9E9wql6sSbuz5NU0dQmrNxR+Bos2YKY3YcRfrDK0lNxpwarKovCp76o2/MQv1iIMgHryV05ET8lUD2bMReYKnWDIDbTscXijnccFdFA+akrDAR3NUunksqkdO+YfDbJV4dUAARDLeaARS9Ouvvnmj42RI0CwxC3//PXWD1IPSPyogP9BSRwmL5ctJbmUsAj0kVwHDkzj3lk4yGMvbmLkTh7k+rwg8BoaDTQjOQCtYh46yVnfTTGDYswne2KcB/trx5Frn9JVuAd5qmMQ+mrOgyxIyjjMTBuz+x81KWT9sQNwPRnPl9CwRB3DY9gtcrDzS3Qjxd7JXzVZnSCaFy/Z5GcuUPp9bebos+DWf/fl8C+T9n1kuXjm+UjAnpEmuZNJWEuY/5jNoyCmi64MQqoYqq/uRUrXaSdBd0UtqezNmBUa36PjqA1pAyA8lH9Tkh4tq+/Vx3loZKhKa7RXdzeNjt1kR2eFL2JzOqy7iF5j77RHn7PlzuwvxnSXkZRS2lWBT2S+gHKEin+jReU=
  app:
    master: eliram-blog
    staging: eliram-blog-staging
